/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb59f",
        "tertiary": "#5b5c5a",
        "surface-variant": "#e0e3e6",
        "background": "#f7f9fc",
        "tertiary-fixed": "#e3e2e0",
        "surface-container-high": "#e6e8eb",
        "surface-bright": "#f7f9fc",
        "on-tertiary-fixed-variant": "#464745",
        "surface-container-low": "#f2f4f7",
        "on-secondary-container": "#636262",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fc",
        "on-secondary-fixed-variant": "#474746",
        "surface-tint": "#9c4328",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e6",
        "on-primary-fixed": "#3a0a00",
        "on-error-container": "#93000a",
        "on-surface-variant": "#56423d",
        "inverse-primary": "#ffb59f",
        "outline": "#89726c",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#1a1c1a",
        "secondary-container": "#e2dfde",
        "on-primary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#7d2c13",
        "outline-variant": "#dcc1b9",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "tertiary-container": "#747572",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdbd1",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f4",
        "primary": "#994125",
        "on-tertiary-container": "#fdfcf9",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c7c6c4",
        "surface-dim": "#d8dadd",
        "inverse-surface": "#2d3133",
        "secondary": "#5f5e5e",
        "surface-container": "#eceef1",
        "primary-container": "#b8583b",
        "terracotta": "#C15F41",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "24px",
      },
      spacing: {
        "section-gap": "120px",
        "margin-mobile": "20px",
        gutter: "32px",
        "container-max": "1280px",
        unit: "8px",
      },
      fontFamily: {
        "body-md": ["Manrope"],
        "headline-md": ["Noto Serif"],
        "body-lg": ["Manrope"],
        "headline-hero": ["Noto Serif"],
        display: ["Noto Serif"],
        "headline-lg": ["Noto Serif"],
        "label-caps": ["Manrope"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-hero": ["72px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "500" }],
        display: ["84px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      boxShadow: {
        soft: "0px 12px 32px rgba(26,26,26,0.04)",
        "soft-hover": "0px 24px 48px rgba(26,26,26,0.08)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
